### ISSUE TITLE
Connected component childContextTypes ignored

### ISSUE THREAD

**Issue by izziaraffaele** [yonatanmn/Cartiv#10]
I have a component which provides a context prop to its children. If I connect this component to a store using the es7 decorator I get the following error message even if my component defines bot `childContextTypes` and `getChildContext()`

Error message:
`childContextTypes must be defined in order to use getChildContext().`

Removing the decorator the code works as espected

**Comment by yonatanmn** [comment]
Hey, 
If you use more decorators (not only Cartiv's) The order is important. 
Try putting `@Connector` just above the component. 
If it's not working please provide the component's code
