### ISSUE TITLE
No store Webpack HMR on React Native

### ISSUE THREAD

**Issue by aviadhahami** [yonatanmn/Cartiv#12]
Hi!
First - Great thing you've got here! thanks!
Second - I'm trying to use your library on my RN project and I've encountered the following case:
On the first render (right after the _initial_ compilation and install onto the device) the store's state propagate down properly.
Every HMR performed afterwards - the store state doesn't propagate down.

I've followed your README where you've stated that in order to use HMR with stores I should include 

``` javascript
createStore.allowHMR(module, textStore);
```

However, I get this yielded
![image](https://cloud.githubusercontent.com/assets/7353632/17347225/56e7f370-5917-11e6-8da8-a594bcccb669.png)

Any idea about what's going on there and/or how to fix?

note: I am using babel's `react-native-stage-0/decorator-support` preset in order to use the ES7 decorators on my classes.

Thanks!

**===EDIT===**
Further inspecting this I've found that [allowHMRinStore.js#L18](https://github.com/yonatanmn/Cartiv/blob/master/src/allowHMRinStore.js#L18) is the trouble making spot.
Is it intentional that there's no `if` over there? (unlike with `if (_module.hot.data)` on the preceding block) ?

When logging the `module` passed as argument to `allowHMR`, this is what I get:
![image](https://cloud.githubusercontent.com/assets/7353632/17347480/d1032c1e-5918-11e6-84a7-f191b113a0fc.png)
So definitely there's no `_module.hot.dispose` on this object what so ever.

Hope this help in any way

**Comment by yonatanmn** [comment]
Hey.  thanks.

react native uses some kind of a replica to node module system, but with out full coverage.
I've reported this issue to RN [here](https://github.com/facebook/react-native/issues/8558).

until they solves it, just remove the `allowHMR` line. 
every thing will still work, but changes to store might require a reload.

**Comment by aviadhahami** [comment]
> I've reported this issue to RN here.

Kudos :+1: 
Will follow

**Comment by aviadhahami** [comment]
React is has been.
