### ISSUE TITLE
Can not read property trigger of undefined

### ISSUE THREAD

**Issue by aviadhahami** [yonatanmn/Cartiv#9]
Hey :)
I'm trying to learn your library and ran into trouble when trying to `setState` in a store.
Here's my specific function (just a `setState` and some ajax)
![image](https://cloud.githubusercontent.com/assets/7353632/15913271/a0816482-2de1-11e6-92c5-0625317441bb.png)
[[Full store source code]](https://github.com/aviadhahami/HomeWorkThirdYearSecondSemester/blob/cartiv/JS/Ex03/Aviad/app/stores/authStore.js#L32).

Now, when trying to change a state (even in the most simple way) I bump into this:
![image](https://cloud.githubusercontent.com/assets/7353632/15913405/74d72fbe-2de2-11e6-88eb-dade8c1d014f.png)

Now, given that I know that dear `Babel` sometimes turns `this` into `undefined`, I looked at the `bundle.js` file and saw it looked ok:
![image](https://cloud.githubusercontent.com/assets/7353632/15913427/9d0dbe9e-2de2-11e6-93cb-e9bbe55854a0.png)

This leaves me with no good ideas of what happened. Any clue?

**Comment by aviadhahami** [comment]
Ok, 
Debugged it and found it was caused due to me attempting to update states unappropriately (modified the state object itself #NoobMe)

Guess this can be closed :+1: 
@yonatanmn - FYI I've just finished my app (used Cartiv of-course) that has auth-flow and some other nice stuff, [if you wanna check it out](https://github.com/aviadhahami/HomeWorkThirdYearSecondSemester/tree/master/JS/Ex03/Aviad)

**Comment by yonatanmn** [comment]
Hey, sorry for late response, been out of technology for the last days.
Glad you worked it out
